### ISSUE TITLE
Reload command does not check for new folders

### ISSUE THREAD

**Issue by LucaFontanot** [onebeastchris/GeyserPackSync#26]
How to reproduce
While the server is on, create a new folder with a server name in the plugin folder.
Run /reloadpacks
The plugin will not find the newly created folder

**Comment by onebeastchris** [comment]
You shouldn't create folders on your own - you need to add them to the config file instead. Then, a reload should properly create & read from the folder

**Comment by LucaFontanot** [comment]
I have done, so, but no folders are created automatically with reload command. You have to restart the server
